package com.github.odaridavid.weatherapp.model

enum class SupportedLanguage(val languageName: String, val languageValue: String) {
    AFRIKAANS("Afrikaans", "af"),
    ALBANIAN("Albanian", "al"),
    ARABIC("Arabic", "ar"),
    AZERBAIJANI("Azerbaijani", "az"),
    BULGARIAN("Bulgarian", "bg"),
    CATALAN("Catalan", "ca"),
    CZECH("Czech", "cz"),
    DANISH("Danish", "da"),
    GERMAN("German", "de"),
    GREEK("Greek", "el"),
    ENGLISH("English", "en"),
    BASQUE("Basque", "eu"),
    PERSIAN("Persian (Farsi)", "fa"),
    FINNISH("Finnish", "fi"),
    FRENCH("French", "fr"),
    GALICIAN("Galician", "gl"),
    HEBREW("Hebrew", "he"),
    HINDI("Hindi", "hi"),
    CROATIAN("Croatian", "hr"),
    HUNGARIAN("Hungarian", "hu"),
    INDONESIAN("Indonesian", "id"),
    ITALIAN("Italian", "it"),
    JAPANESE("Japanese", "ja"),
    KOREAN("Korean", "kr"),
    LATVIAN("Latvian", "la"),
    LITHUANIAN("Lithuanian", "lt"),
    MACEDONIAN("Macedonian", "mk"),
    NORWEGIAN("Norwegian", "no"),
    DUTCH("Dutch", "nl"),
    POLISH("Polish", "pl"),
    PORTUGUESE("Portuguese", "pt"),
    PORTUGUESE_BRAZIL("Português  Brasil", "pt_br"),
    ROMANIAN("Romanian", "ro"),
    RUSSIAN("Russian", "ru"),
    SWEDISH("Swedish", "sv, se"),
    SLOVAK("Slovak", "sk"),
    SLOVANIAN("Slovenian", "sl"),
    SPANISH("Spanish", "sp, es"),
    SERBIAN("Serbian", "sr"),
    THAI("Thai", "th"),
    TURKISH("Turkish", "tr"),
    UKRAINIAN("Ukrainian", "ua, uk"),
    VIETNAMESE("Vietnamese", "vi"),
    CHINESE_SIMPLIFIED("Chinese Simplified", "zh_cn"),
    CHINESE_TRADITIONAL("Chinese Traditional", "zh_tw"),
    ZULU("Zulu", "zu")
}
